apiVersion: v1
kind: Service
metadata:
  name: {{ include "food-frenzy-helm.fullname" . }}
  labels:
    {{- include "food-frenzy-helm.app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.app.port }}
    protocol: TCP
  selector:
    {{- include "food-frenzy-helm.app.selectorLabels" . | nindent 4 }}